#!/bin/sh

# micropython-stubber pre-commit hook

# Patch Branches
PATCHES=`git for-each-ref refs/heads/patch --format='%(refname)' | cut -d/ -f3-`

# Update Patches
ROOT=`git rev-parse --show-toplevel`

# Make Patches
for patch in "${PATCHES[@]}"; do
	NAME=`echo $patch | cut -c 7-`
	OUT="$ROOT/patches/$NAME.patch"
	git format-patch --stdout --root "$patch" -1 > "$OUT"
	# Stage
	git add "$OUT"
done


