# template used by the release drafter workflow 
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'exclude-from-changelog'
categories:
  - title: '⚠️ Breaking changes'
    label: 'breaking'
  - title: '🚀 Features'
    label: 
      - 'feature'
      - 'enhancement'
  - title: '📘 Documentation'
    label: 'documentation'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'

template: |
  ## What's changed
  $CHANGES
  ## Contributors to this release
  $CONTRIBUTORS