rule_settings:
  enable: 
  - default
  - snake-case-functions
  - docstrings-for-modules
  - require-parameter-annotation
  - no-wildcard-imports
  - no-long-functions
  # - require-return-annotation  # Pylance does infer this quite well already
  # - docstrings-for-functions

  disable:
  - use-contextlib-suppress
  - use-fstring-for-formatting
  - use-fstring-for-concatenation
  - do-not-use-staticmethod
  - name-type-suffix

  python_version: '3.8'

  rule_types:
    - refactoring
    - suggestion
    - comment

ignore:
  - board/*_*.py
  - board/logging.py
  - minified/
  - .venv/
  - tests/*
  - '*_test.py'
  - repos/
  - .git/
  - .github/
  - src/stubber/board
  - src/stubber/minified
  
rules:
- id: no-wildcard-imports
  pattern: from ${module} import *
  description: Do not use wildcard imports
  explanation: |
      Use import statements for packages and modules only, not for individual classes or functions.

      - Use `import x` for importing packages and modules.
      - Use `from x import y` where `x` is the package prefix and `y` is the module name with no prefix.
      - Use `from x import y as z` if two modules named `y` are to be imported, if `y` conflicts with a top-level name defined in the current module, or if `y` is an inconveniently long name.
      - Use `import y as z` only when `z` is a standard abbreviation (e.g., np for numpy).
  tags:
    - google-python-style-guide
    - gpsg
    - gpsg-import
  tests:
    - match: from numpy import *
    - match: from pandas.series import *
    - match: from .something import *
    - no-match: from math import sin
