# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for Composer
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`  
    directory: "/"
    schedule:
      interval: "daily"
    