from typing import Any

log_level: int

def log_error(*args) -> None: ...
def log_warn(*args) -> None: ...
def log_info(*args) -> None: ...

class GattError(Exception):
    _status: Any
    def __init__(self, status) -> None: ...

def ensure_active() -> None: ...
def config(*args, **kwargs): ...

_irq_handlers: Any
_shutdown_handlers: Any

def register_irq_handler(irq, shutdown) -> None: ...
def stop() -> None: ...
def ble_irq(event, data): ...

ble: Any
