from .core import ble as ble, log_error as log_error, register_irq_handler as register_irq_handler
from .device import DeviceConnection as DeviceConnection
from typing import Any

_IRQ_L2CAP_ACCEPT: Any
_IRQ_L2CAP_CONNECT: Any
_IRQ_L2CAP_DISCONNECT: Any
_IRQ_L2CAP_RECV: Any
_IRQ_L2CAP_SEND_READY: Any
_listening: bool

def _l2cap_irq(event, data) -> None: ...
def _l2cap_shutdown() -> None: ...

class L2CAPDisconnectedError(Exception): ...
class L2CAPConnectionError(Exception): ...

class L2CAPChannel:
    _connection: Any
    our_mtu: int
    peer_mtu: int
    _cid: Any
    _status: int
    _stalled: bool
    _data_ready: bool
    _event: Any
    def __init__(self, connection) -> None: ...
    def _assert_connected(self) -> None: ...
    async def recvinto(self, buf, timeout_ms: Any | None = ...): ...
    def available(self): ...
    async def send(self, buf, timeout_ms: Any | None = ...) -> None: ...
    async def flush(self, timeout_ms: Any | None = ...) -> None: ...
    async def disconnect(self, timeout_ms: int = ...) -> None: ...
    async def disconnected(self, timeout_ms: int = ...) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_traceback) -> None: ...

async def accept(connection, psn, mtu, timeout_ms): ...
async def connect(connection, psn, mtu, timeout_ms): ...
