packages = [
    "github:josverl/micropython-stubs/mip/typing.json",
    "github:josverl/micropython-stubber/src/stubber/board/createstubs.py",
]


# interpreter = "https://cdn.jsdelivr.net/npm/@micropython/micropython-webassembly-pyscript@1.27.0-preview-282/micropython.mjs"
# interpreter = "https://cdn.jsdelivr.net/npm/@micropython/micropython-webassembly-pyscript@1.26.0/micropython.mjs"

# Local pyscript variant - Note that not all released version work with pyscript
# interpreter = "./webassembly/webassembly-pyscript-v1.24.1/micropython.mjs"  # OK 
# interpreter = "./webassembly/webassembly-pyscript-v1.25.0/micropython.mjs"  # OK 
# interpreter = "./webassembly/webassembly-pyscript-v1.26.0/micropython.mjs"  # <-- Does not load 
# interpreter = "./webassembly/webassembly-pyscript-v1.26.1/micropython.mjs"  # <-- Does not load 
# interpreter = "./webassembly/webassembly-pyscript-v1.27.0-preview/micropython.mjs"

# Standard webassembly variant - will fail due to missing modules:
# no module named 'pathlib'
# no module named 'pyscript'
# interpreter = "./build-standard/micropython.mjs"
