# make_stub_files: Tue 23 Apr 2019 at 22:52:01

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class SSD1306:
    def __init__(self, width: Any, height: Any, external_vcc: Any) -> None: ...
    def init_display(self) -> None: ...
    def poweroff(self) -> None: ...
    def contrast(self, contrast: Any) -> None: ...
    def invert(self, invert: Any) -> None: ...
    def show(self) -> None: ...
    def fill(self, col: Any) -> None: ...
    def pixel(self, x: Any, y: Any, col: Any) -> None: ...
    def scroll(self, dx: Any, dy: Any) -> None: ...
    def text(self, string: Any, x: Any, y: Any, col: Any=1) -> None: ...
class SSD1306_I2C(SSD1306):
    def __init__(self, width: Any, height: Any, i2c: Any, addr: Any=60, external_vcc: Any=bool) -> None: ...
    def write_cmd(self, cmd: Any) -> None: ...
    def write_data(self, buf: Any) -> None: ...
    def poweron(self) -> None: ...
class SSD1306_SPI(SSD1306):
    def __init__(self, width: Any, height: Any, spi: Any, dc: Any, res: Any=None, cs: Any=None, external_vcc: Any=bool) -> None: ...
    def write_cmd(self, cmd: Any) -> None: ...
    def write_data(self, buf: Any) -> None: ...
    def poweron(self) -> None: ...
