# This workflow will :
# update mip packages in the \mip folder

name: mip

on:
  workflow_dispatch:
  push:
    paths:
      - "src/stubber/board/**"

jobs:
  mip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #----------------------------------------------

      - name: Install poetry # poetry is not in the default image
        run: pipx install poetry==1.3.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Replace with the Python version you're using
          cache: "poetry"

      - name: Install stubber
        run: poetry install --with dev --no-interaction

      - name: make all variants
        run: |
          poetry run stubber make-variants
          poetry run stubber make-variants --target ./mip/v5 --version 1.18
          poetry run stubber make-variants --target ./mip/v6 --version 1.19.1

      - name: run test on minified/createstubs.by
        run: |
          poetry run pytest -m minified

      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update mip packages
