name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #----------------------------------------------
      # poetry is not in the default image
      #----------------------------------------------
      - name: Install Poetry
        run: pipx install poetry==1.3.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build project for distribution
        run: poetry build

      # - name: Check Version
      #   id: check-version
      #   run: |
      #     [[ "$(stubber version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
      #       || echo ::set-output name=prerelease::true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
